version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - .:/code
    ports:
      - "8010:8010"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example